# Generated by Django 5.2.10 on 2026-03-09 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_id_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Password can contain letters, numbers and special characters', regex='^[A-Za-z0-9@#$%^&+=!]*$')])),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^[0-9]{10}$')])),
                ('address', models.TextField()),
                ('total_gathering', models.PositiveIntegerField()),
                ('specification', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(upload_to='restaurant_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='restaurant_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='restaurant_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
