# Generated by Django 5.2.10 on 2026-03-09 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits', regex='^[0-9]{6}$')]),
        ),
    ]
