# Generated by Django 5.2.10 on 2026-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_restaurant_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/'),
        ),
    ]
